# Generated by Django 4.1 on 2022-08-20 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bqapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='main_job_id',
            new_name='main_job',
        ),
        migrations.RenameField(
            model_name='subtask',
            old_name='job_id',
            new_name='sub_job_id',
        ),
    ]
