# Generated by Django 4.1 on 2022-08-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bqapp', '0002_rename_main_job_id_subtask_main_job_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtask',
            old_name='main_job',
            new_name='main_task',
        ),
    ]
