# Generated by Django 4.1 on 2022-08-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bqapp', '0003_rename_main_job_subtask_main_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtask',
            name='parallel_job_id_list',
            field=models.JSONField(default=list, verbose_name='並列ジョブIDリスト'),
        ),
    ]
